language: csharp
script:
  - xbuild /p:Configuration=Debug BlockIoLib.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore BlockIoLib.sln
after_script:
  - nunit-console BlockIoLib.UnitTests/bin/Debug/netcoreapp3.0/BlockIoLib.UnitTests.dll